export const RoutesUrls = {
  mon: 'https://edu.gov.kg/',
  root: `/${import.meta.env.VITE_BASE}/`,
  login: `/${import.meta.env.VITE_BASE}/login`,
  cabinet: `/${import.meta.env.VITE_BASE}/cabinet`,
  main: `/${import.meta.env.VITE_BASE}/cabinet/main`,
  faculty: `/${import.meta.env.VITE_BASE}/cabinet/faculty`,
  direction: `/${import.meta.env.VITE_BASE}/cabinet/direction`,
  specialty: `/${import.meta.env.VITE_BASE}/cabinet/specialty`,
  disciplines: `/${import.meta.env.VITE_BASE}/cabinet/disciplines`,
  employees: `/${import.meta.env.VITE_BASE}/cabinet/employees`,
  curriculum: `/${import.meta.env.VITE_BASE}/cabinet/curriculum`,
  graduates: `/${import.meta.env.VITE_BASE}/cabinet/graduates`,
  grades: `/${import.meta.env.VITE_BASE}/cabinet/grades`,
  organization: `/${import.meta.env.VITE_BASE}/cabinet/organization`,
  reports: `/${import.meta.env.VITE_BASE}/cabinet/reports`,
  settings: `/${import.meta.env.VITE_BASE}/cabinet/settings`,
  chatPage: `/${import.meta.env.VITE_BASE}/cabinet/chat-page`,
  help: `/${import.meta.env.VITE_BASE}/cabinet/help`,
  privacyPolicy: `/${import.meta.env.VITE_BASE}/cabinet/privacyPolicy`,
  manual: `/${import.meta.env.VITE_BASE}/cabinet/manual`,
  logout: `/${import.meta.env.VITE_BASE}/cabinet/logout`,
  notFound: `/${import.meta.env.VITE_BASE}/not-found`,
};
